version: '3.9'

services: 
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    user: root
    restart: always
    networks:
      - anti-media
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: "myPassword!s3cure"
    volumes:
      - ./.data/mssql:/var/opt/mssql/data
    
  media-api:
    build:
      context: ./
    restart: always
    ports:
      - "7126:80"
      - "7125:443"
    networks:
      - anti-media
    environment:
      "ConnectionStrings:DefaultConnection": "Server=mssql;Database=anti-media;user id=sa;password=myPassword!s3cure;"

networks:
  anti-media:
    name: AntiSocial Media Network